---
title: find_order_parameters
type: object
properties:
  order_id:
    type: string
    description: Unique identifier for the order.
    example: order_12345
  customer_id:
    type: string
    description: Unique identifier for the customer.
    example: customer_101
  product_id:
    type: string
    description: Unique identifier for the product.
    example: product_202
  order_date_start:
    type: string
    format: date
    description: Start date for the order search range.
    example: 2025-03-01
  order_date_end:
    type: string
    format: date
    description: End date for the order search range.
    example: 2025-03-31
