export const data = {
  keyPartnerships: {
    title: "Key partnerships",
    defaultItems: [
      "Who are our key suppliers?",
      "Which key resources are we acquiring from partners?",
      "Which key activities our partners perform?",
      { head: "Motivation for partnerships " },
      [
        "Optimization and economy",
        "Reduction of risk and uncertainty",
        "Acquisition of particular resources and activities",
      ],
    ],
    icon: "mat-share",
  },
  keyActivities: {
    title: "Key activities",
    defaultItems: [
      "What key activities do our value propostions require?",
      "Our distribution channels?",
      "Customer relationships?",
      "Revenue Streams?",
      { head: "Categories" },
      ["Production", "Problem solving", "Platform / network"],
    ],
    icon: "mat-check",
  },
  valuePropositions: {
    title: "Value propositions",
    defaultItems: [
      "Which value do we deliver to the customer?",
      "Which one of our customer's problems are we helping to solve?",
      "What bundles of products and services are we offering to each customer segment?",
      "Which customer needs are we satisfying",
      { head: "Characteristics" },
      [
        "Newness",
        "Performance",
        "Customization",
        '"Getting Job Done"',
        "Design",
        "Brand / status",
        "Price",
        "Cost Reduction",
        "Risk Reduction",
        "Accessibility",
        "Convenience / usability",
      ],
    ],
    icon: "mat-featured_seasonal_and_gifts",
  },
  customerRelationships: {
    title: "Customer relationships",
    defaultItems: [
      "What type of relationship each customer segment expects?",
      "Which ones have we established?",
      "How are they integrated with rest of the biz. model?",
      "How much they cost us?",
      { head: "Examples" },
      [
        "Personal assistance",
        "Self-service",
        "Automated services",
        "Communities",
        "Co-creation",
      ],
    ],
    icon: "mat-favorite",
  },
  customerSegments: {
    title: "Customer segments",
    defaultItems: [
      "For whom are we creating value?",
      "Who are our most important customers?",
      { head: "Examples" },
      ["Mass market", "Niche market", "Segmented", "Multi-sided platform"],
    ],
    icon: "mat-group",
  },
  keyResources: {
    title: "Key resources",
    defaultItems: [
      "What key resources our value proposition requires?",
      "Our distribution channels? Customer relationships?",
      "Revenue Streams?",
      { head: "Types of resource" },
      [
        "Physical",
        "Intellectual (brand, patents, copyrights, data)",
        "Human",
        "Financial",
      ],
    ],
    icon: "mat-factory",
  },
  costStructure: {
    title: "Cost structure",
    defaultItems: [
      "What are most important costs inherent to our business model?",
      "Which key resources are most expensive?",
      "Which key activities are most expensive?",
      { head: "Is your business more?" },
      [
        "Cost driven (cost structure, low price prop, maximum automation, extensive outsourcing)",
        "Value driven (focused on value creation, premium value prop)",
      ],
    ],
    icon: "mat-sell",
  },
  revenueStreams: {
    title: "Revenue streams",
    defaultItems: [
      "For what value are our customers willing to pay?",
      "What are they currently paying for?",
      "How are they paying?",
      "How would they prefer to pay?",
      "How much each revenue stream contributes overall?",
    ],
    icon: "mat-payments",
  },
  channels: {
    title: "Channels",
    defaultItems: [
      "Through which channels our customer segments want to be reached?",
      "How are we reaching them now?",
      "How are channels integrated?",
      "Which ones work best?",
      "Which ones are most cost efficient?",
      "How are we integrating them with customer routines?",
    ],

    icon: "mat-local_shipping",
  },
};
