---
title: create_order_parameters
type: object
properties:
  order_id:
    type: string
    description: Unique identifier for the order.
    example: order_12345
  customer_id:
    type: string
    description: Unique identifier for the customer placing the order.
    example: customer_789
  order_date:
    type: string
    format: date-time
    description: The date and time when the order was placed.
    example: 2025-03-04T11:30:00Z
  items:
    type: array
    description: List of items included in the order.
    items:
      type: object
      properties:
        item_id:
          type: string
          description: Unique identifier for the item.
          example: item_456
        quantity:
          type: integer
          minimum: 1
          description: Quantity of the item ordered.
          example: 2
        unit_price:
          type: number
          minimum: 0
          description: Price per unit of the item.
          example: 19.99
      required:
        - item_id
        - quantity
        - unit_price
  shipping_address:
    type: object
    description: The shipping address for the order.
    properties:
      street:
        type: string
        description: Street address.
        example: 123 Main Street
      city:
        type: string
        description: City of the address.
        example: Amsterdam
      postal_code:
        type: string
        description: Postal code.
        example: 1011AB
      country:
        type: string
        description: Country of the address.
        example: Netherlands
    required:
      - street
      - city
      - postal_code
      - country
required:
  - order_id
  - customer_id
  - order_date
  - items
  - shipping_address
