name: Install dependencies
description: Installs dependencies.
runs:
  using: "composite"
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install project dependencies
      shell: bash
      run: npm ci

    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps
