name: Local tests
description: Run tests.
runs:
  using: "composite"
  steps:
    - name: Test
      shell: bash
      run: npm run test

    - name: Upload test report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
