name: Commit in pull-request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test commit in pull-request
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies

      ### Disabled while tests pass locally and fail in the workflow
      # - name: Run local tests
      #   uses: ./.github/actions/test_local
